.TH ASH-EUSES 1 2020-06-11 git.suugaku.co.uk "General Commands Manual"
.SH NAME
.BR ash-euses " \- a rewrite of " euses "(1) for modern Gentoo-like systems"
.SH SYNOPSIS
.B ash-euses
.RI "[" "OPTIONS" "]... [" SUBSTRING "]..."
.SH DESCRIPTION
.BR ash-euses " searches for substrings in USE-description files in the "
various repositories, as enumerated by the contents of the
.IB PORTAGE_CONFIGROOT /repos.conf/
directory. Each regular file in the directory is assumed to be a
repository-description and parsed, extracting the
.BR location " attribute to find the base of the repository. Most users will"
only care about the
.BR ::gentoo " repository, however"
.BR ash-euses " is capable of scanning an arbitrary number of repositories."
.IR PORTDIR " is also respected as an environment variable or entry in"
.BR make.conf ", however it is highly discouraged due to deprecation by the "
Gentoo developers.

.BR ash-euses " scans files matching"
.IB BASE /profiles/*.desc
where
.IR BASE " is the value from the"
.BR location " attribute, also recursing into the " desc/ " directory."
.SH OPTIONS
.TP
.BR "\-\-help", " \-h"
Print a short summary of the syntax commands and quit.
.TP
.BR "\-\-version", " \-v"
Prepend the output with the versioning, author, and licence information.
.TP
.BR "\-\-list\-repos", " \-r"
Prepend the output with a list of the repository names and locations, collected
from the configuration files in the
.IB PORTAGE_CONFIGROOT /repos.conf/
directory.
.TP
.BR "\-\-repo\-names", " \-n"
Append the repository name to every match, in the form of
.BI :: repo
.RI where " repo"
is the name taken from the repository-configuration file.
.TP
.BR "\-\-repo\-paths", " \-p " "(implies " \-\-repo\-names )
Prepend the file location and repository to the match, in the form
.IB file :: name :: match
.RI "where " file 
is the path of the description file in which the match was found.
.TP
.BR "\-\-strict", " \-s"
Restrict the searching to the USE-flag field, as opposed to searching the entire
file. This will significantly reduce the yield of the search on most systems.
This behaviour might become the default in the future, replaced with a
.BR \-\-lax " option."
.TP
.BR "\-\-quiet", " \-q"
.RI "Suppress the complaint message that arises when " PORTDIR " is detected"
.RB "on the system. See " VARIABLES " for more information regarding the "
issues of using
.IR PORTDIR " on modern Gentoo-like systems."
.TP
.BR "\-\-no\-case", " \-c"
Perform a case-insensitive search across all the files/buffers. This may have an
extremely small impact on performance, but utilises various C.P.U.\ extensions
similar to
.BR strstr "(3)."
.TP
.BR "\-\-portdir", " \-d"
.RB "Attempt to use the deprecated " PORTDIR " variable if applicable. If this"
.RB " option is set without the " -q " option, a warning will be issued if"
.BR PORTDIR " is detected and used."
.TP
.BR "\-\-print\-needles", " \-e"
For each search result, print the relevant needle in the form
.RI ( needle ) " match" ". This option can be combined with the "
.BR --repo-names " and " --repo-paths " options."
.TP
.BR "\-\-no\-interrupt", " \-i"
Do not interrupt the search results with a non-fatal error/warning on
.BR stderr ". These mainly appear with warnings regarding errors with the"
loading of a temporary buffer to seamlessly print a trans-buffer line. Even if
these warnings are suppressed, it is likely that a fatal error will appear
shortly after, as the system could not perform an
.BR fread "(3) call on the USE-description file."
.TP
.BR "\-\-package", " \-k"
Restrict the search to category-package files, excluding description files of
global USE-flags. In practice, this only includes files containing
.BR *.local " in the search."
.TP
.BR \-\-
.RB "If " \-\- " is passed on the command-line, all further arguments are"
considered as substrings.
.SH VARIABLES
.TP
.B PORTAGE_CONFIGROOT
If set in the environment, this variable can be used to modify the directory in
which the Portage configuration files are stored. For example, for a Gentoo
.RB "root partition mounted in the " /mnt/gentoo
.RI "directory, " PORTAGE_CONFIGROOT " can be set to force "
.BR ash-euses " to search "
.BR /mnt/gentoo/etc/portage/repos.conf " for repository-configuration files."
.TP
.B PORTDIR
This is a deprecated, albeit widely used, environment variable or
.BR make.conf " option to specify the base of the " ::gentoo " repository. On "
.RB "very old systems, this defaults to " /usr/portage ". If"
.BR ash-euses " detects the usage of "
.IR PORTDIR " in either of these locations, it issues a warning and ignores the"
.BR " repos.conf " "directory. For users and administrators desiring multiple "
repositories/overlays, it is highly recommended that the new
.BR " repos.conf " "system is preferred. Use the " "\-\-quiet" " command-line"
option to suppress the
.IR PORTDIR " warning."
.SH FILES
.TP
.B repos.conf/
The
.IB $PORTAGE_CONFIGROOT /repos.conf/
directory contains the repository-configuration files for Portage, containing a
human-readable name, and base directory. Files inside this directory usually are
suffixed with
.BR .conf ", however this is not required by the Gentoo specification."
.BR ash-euses " will fail if the file " gentoo.conf " is not found in the"
directory.
.TP
.B make.conf
.IR $PORTAGE_CONFIGROOT/make.conf " is the primary configuration for Portage, "
describing various key-value pairs to be used by ebuilds.
.BR ash-euses " uses this file exclusively for the extraction of the "
.IR PORTDIR " key."
.TP
.B profiles/{,desc/}*.desc
.IB BASE /profiles/{,desc/}*.desc
.RB "are the USE-description files searched " ash-euses ", in which
.IR BASE " is the base of the current repository
.RB "directory. If the " --package " option is set, the searching pattern is"
.RB "restricted to " profiles/{,desc/}*.local*.desc .
.SH EXAMPLES
.TP
.B ash-euses -prv qt5
Prepending the output with version information and a list of repositories,
search the files for the "qt5" substring. Each entry is appended with the name
and location of the repository in which the match was found.
.TP
.B ash-euses -sn -- --ipsum
Search the files in all repositories for USE-flag fields ending in the "--ipsum"
substring, appending the name of the relevant repository to each result.
.TP
.B PORTAGE_CONFIGROOT=/mnt/gentoo ash-euses -r
.RB "Using the " /mnt/gentoo/etc/portage " configuration directory, list all"
.RB "repositories described in the " repos.conf " directory."
.SH SEE ALSO
.BR "euses" "(1), " "emerge" "(1), " "make.conf" "(5), " "portage" "(5), "
.BR "ebuild" "(1), " glob (3)
.SH AUTHOR
.RI "Ashley Dixon <" ash@suugaku.co.uk >
